Repository WaterdogPE/WaterdogPE, pull requests merged in 2022-10, with the labels that each got.

#232 Texture Pack Encryption key support
  src/main/java/dev/waterdog/waterdogpe/ProxyServer.java
  src/main/java/dev/waterdog/waterdogpe/packs/PackManager.java
  src/main/java/dev/waterdog/waterdogpe/packs/types/ResourcePack.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#216 Multi-port support
  src/main/java/dev/waterdog/waterdogpe/ProxyServer.java
  src/main/java/dev/waterdog/waterdogpe/network/ProxyListener.java
  src/main/java/dev/waterdog/waterdogpe/query/QueryHandler.java
  src/main/java/dev/waterdog/waterdogpe/utils/config/ProxyConfig.java
Labels: enhancement, hacktoberfest-accepted

#240 Support MCBE 1.19.40
  pom.xml
  src/main/java/dev/waterdog/waterdogpe/network/protocol/ProtocolConstants.java
  src/main/java/dev/waterdog/waterdogpe/network/protocol/ProtocolVersion.java
  src/main/java/dev/waterdog/waterdogpe/network/protocol/codec/BedrockCodec557.java
Labels: protocol, protocol/version-upgrade
